services:
  - type: web
    name: pokecalc
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: pokecalc-db
          property: connectionString
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        value: pokecalc-121d3
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false

databases:
  - name: pokecalc-db
    plan: free